# Generated by Django 5.1 on 2024-09-03 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nadzor_num', models.CharField(blank=True, max_length=45, null=True)),
                ('nadzor_date', models.DateField(blank=True, null=True)),
                ('works', models.CharField(blank=True, max_length=45, null=True)),
                ('interval', models.CharField(blank=True, max_length=45, null=True)),
                ('diameter', models.CharField(blank=True, max_length=45, null=True)),
                ('length', models.CharField(blank=True, max_length=45, null=True)),
                ('material', models.CharField(blank=True, max_length=45, null=True)),
                ('agent', models.CharField(blank=True, max_length=45, null=True)),
                ('agent_phone', models.CharField(blank=True, max_length=45, null=True)),
                ('meet_date', models.DateField(blank=True, null=True)),
                ('meet_place', models.CharField(blank=True, max_length=45, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='core.order')),
            ],
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
