# Generated by Django 5.1 on 2024-09-12 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0005_call_zone'),
        ('core', '0005_remove_order_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='agent',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Представитель'),
        ),
        migrations.AlterField(
            model_name='call',
            name='agent_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Контакт'),
        ),
        migrations.AlterField(
            model_name='call',
            name='diameter',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Диаметр'),
        ),
        migrations.AlterField(
            model_name='call',
            name='interval',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Интервал'),
        ),
        migrations.AlterField(
            model_name='call',
            name='length',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Длина'),
        ),
        migrations.AlterField(
            model_name='call',
            name='material',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='call',
            name='meet_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата встречи'),
        ),
        migrations.AlterField(
            model_name='call',
            name='meet_place',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Место встречи'),
        ),
        migrations.AlterField(
            model_name='call',
            name='nadzor_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата договора ТН'),
        ),
        migrations.AlterField(
            model_name='call',
            name='nadzor_num',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Договор на ТН'),
        ),
        migrations.AlterField(
            model_name='call',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='core.order', verbose_name='Кодовое название'),
        ),
        migrations.AlterField(
            model_name='call',
            name='works',
            field=models.TextField(blank=True, null=True, verbose_name='Работы'),
        ),
        migrations.AlterField(
            model_name='call',
            name='zone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Район'),
        ),
    ]
