# Generated by Django 5.1 on 2024-11-08 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0006_alter_call_agent_alter_call_agent_phone_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Call',
        ),
    ]
