# Generated by Django 5.1 on 2024-09-09 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_ordermanager_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='zone',
        ),
    ]
