# Generated by Django 5.1 on 2024-11-08 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_order_zone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nadzor_num', models.CharField(blank=True, max_length=100, null=True, verbose_name='Договор на ТН')),
                ('nadzor_date', models.DateField(blank=True, null=True, verbose_name='Дата договора ТН')),
                ('works', models.TextField(blank=True, null=True, verbose_name='Работы')),
                ('interval', models.CharField(blank=True, max_length=100, null=True, verbose_name='Интервал')),
                ('diameter', models.CharField(blank=True, max_length=100, null=True, verbose_name='Диаметр')),
                ('length', models.CharField(blank=True, max_length=100, null=True, verbose_name='Длина')),
                ('material', models.CharField(blank=True, max_length=100, null=True, verbose_name='Материал')),
                ('agent', models.CharField(blank=True, max_length=100, null=True, verbose_name='Представитель')),
                ('agent_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Контакт')),
                ('meet_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата встречи')),
                ('meet_place', models.CharField(blank=True, max_length=255, null=True, verbose_name='Место встречи')),
                ('zone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Район')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='core.order', verbose_name='Кодовое название')),
            ],
        ),
    ]
